# Config map that contains a script to parse the NVCF secrets file and set the environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-parse-nvcf-secrets
  labels:
      {{- include "earth2.labels" . | nindent 4 }}
data:
  # TODO: Would a nested value (secret-key-3 in the link below) cause this to
  # fail? I think adding a wget to fetch jq at runtime might be more robust. Or
  # use a jq init container for this.
  "parse-nvcf-secrets.sh": |
    #!/bin/bash
    # See NVCF documentation for more details
    # https://docs.nvidia.com/cloud-functions/user-guide/latest/cloud-function/secrets.html#secrets-in-helm-chart-functions

    SECRETS_FILE="/var/secrets/secrets.json"
    if [ -f "$SECRETS_FILE" ]; then
        echo "Found secrets file"
        # Remove first and last curly braces, remove whitespace, and split on commas
        secrets=$(cat "$SECRETS_FILE" | tr -d '{}' | tr -d ' ' | tr ',' '\n')

        # Process each line
        while IFS= read -r line; do
            # Skip empty lines
            [ -z "$line" ] && continue

            # Remove quotes and split on colon
            key=$(echo "$line" | cut -d':' -f1 | tr -d '"')
            value=$(echo "$line" | cut -d':' -f2- | tr -d '"')

            # Export the key-value pair
            if [ -z "${!key:+x}" ]; then
                export ${key}="$value"
                echo "Set $key"
            else
                echo "Skipping $key"
            fi
        done <<< "$secrets"
    fi
