[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Example Extension"
description = "An example extension to act as a starting point"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# Path (relative to the root) or content of changelog markdown file for UI.
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
repository = "https://github.com/NVIDIA-Omniverse-blueprints/earth2-weather-analytics"

# One of categories for UI.
category = "example"

# Keywords for the extension
keywords = ["kit", "example"]

# Icon to show in the extension manager
icon = "data/icon.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"

[dependencies]
"omni.ui" = {}
# dependency to give access to the E2CC core apis
"omni.earth_2_command_center.app.core" = {}
# dependency to convert lat,lon to scene space
"omni.earth_2_command_center.app.geo_utils" = {}
# dependency to give allow us to register new features with the viewport
"omni.earth_2_command_center.app.globe_view" = {}

# Main python module this extension provides
[[python.module]]
name = "omni.earth_2_command_center.app.example_extension"

[settings]
# this is how we can configure settings for our extension
exts."omni.earth_2_command_center.app.example_extension".example_setting = true
