# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-added-large-files
      args: [--maxkb=5000]
      exclude: ^(e2cc/.*)
    - id: trailing-whitespace
      exclude: ^(e2cc/.*|helm/|src/k8s/.*/helm/.*|src/tests/files/.*)
    - id: end-of-file-fixer
      exclude: ^(e2cc/.*|helm/|src/k8s/.*/helm/.*|src/tests/files/.*)
    - id: check-yaml
      exclude: ^(e2cc/.*|deploy/helm/|src/tests/files/.*)

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
      exclude: ^(e2cc/.*)

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
    - id: ruff
      args: [--fix]
      exclude: ^(e2cc/.*)

-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
    - id: interrogate
      args: [
          "-vv", "--ignore-init-method", "--ignore-init-module",
          "--ignore-module", "--ignore-private", "--ignore-semiprivate",
          "--ignore-magic", "--fail-under=99", "--exclude=['setup.py', 'test', 'build', 'docs']",
          "--ignore-regex=['forward', 'backward', 'reset_parameters', 'extra_repr', 'MetaData', 'apply_activation','exec_activation']",
          "--color", "--"]
      exclude: ^(e2cc/.*)

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
    - id: markdownlint
      exclude: ^(e2cc/.*)

# -   repo: local
#     hooks:
#     - id: license
#       name: license
#       entry: python test/ci_tests/header_check.py
#       language: python
#       pass_filenames: false
