# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Literal

from ...api.sfno import SfnoPrognostic as SfnoPrognostic_1


class SfnoPrognostic(SfnoPrognostic_1):
    """
    Unrolls SFNO forecasts from an initial condition
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal['federation.fed.site.client1.sfno.SfnoPrognostic'] = (
        'federation.fed.site.client1.sfno.SfnoPrognostic'
    )
    __api_name__: Literal['sfno.SfnoPrognostic'] = 'sfno.SfnoPrognostic'
