# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Literal

from ...api.xarray import ConvertToUint8 as ConvertToUint8_1
from ...api.xarray import RenderUint8ToImages as RenderUint8ToImages_1
from ...api.xarray import VariableNorm as VariableNorm_1


class ConvertToUint8(ConvertToUint8_1):
    """
    Converts the xarray to uint8
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal['federation.fed.site.client1.xarray.ConvertToUint8'] = (
        'federation.fed.site.client1.xarray.ConvertToUint8'
    )
    __api_name__: Literal['xarray.ConvertToUint8'] = 'xarray.ConvertToUint8'


class RenderUint8ToImages(RenderUint8ToImages_1):
    """
    Renders the uint8 to images
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal[
        'federation.fed.site.client1.xarray.RenderUint8ToImages'
    ] = 'federation.fed.site.client1.xarray.RenderUint8ToImages'
    __api_name__: Literal['xarray.RenderUint8ToImages'] = 'xarray.RenderUint8ToImages'


class VariableNorm(VariableNorm_1):
    """
    Computes the p-norm of specified variables in a dataset
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal['federation.fed.site.client1.xarray.VariableNorm'] = (
        'federation.fed.site.client1.xarray.VariableNorm'
    )
    __api_name__: Literal['xarray.VariableNorm'] = 'xarray.VariableNorm'
