# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from nv_dfm_core.api import Advise, NodeParam, Operation, PlaceParam


class CbottleDataGen(Operation):
    """
    Generates synthetic climate data using CBottle3D diffusion model

    Parameters:
        variables: [Accepts: literal input, node input, place input. Discoverable]
            The climate variables to generate (e.g., ['msl', 'tcwv'])
        time: [Accepts: literal input, node input, place input. Discoverable]
            Timestamp string in ISO format (e.g., '2022-09-05T00:00:00')
        n_samples: [Accepts: literal input, node input, place input. Discoverable]
            Number of samples to generate (default: 1)
        seed: [Accepts: literal input, node input, place input. Discoverable]
            Random seed for reproducibility (default: None)
        device: [Accepts: literal input, node input, place input. Discoverable]
            Device to use for model inference. Options: 'cuda', 'cuda:N', 'cpu', or None for auto-select
        lat_lon: [Accepts: literal input, node input, place input. Discoverable]
            Whether to return data on a lat/lon grid or a nested HealPix grid (default: True)

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.cbottle.CbottleDataGen'] = (
        'federation.fed.api.cbottle.CbottleDataGen'
    )
    __api_name__: Literal['cbottle.CbottleDataGen'] = 'cbottle.CbottleDataGen'
    variables: Union[List, NodeParam, PlaceParam, Advise]
    time: Union[str, NodeParam, PlaceParam, Advise]
    n_samples: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    seed: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    device: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
    lat_lon: Optional[Union[bool, NodeParam, PlaceParam, Advise]] = None


class CbottleInfilling(Operation):
    """
    Performs infilling on a dataset using CBottleInfill model to generate additional climate variables

    Parameters:
        dataset: [Accepts: literal input, node input, place input. Discoverable]
            Input xarray.Dataset containing climate data
        input_variables: [Accepts: literal input, node input, place input. Discoverable]
            List of variables to use as input for infilling (e.g., ['u10m', 'v10m', 't2m'])
        sampler_steps: [Accepts: literal input, node input, place input. Discoverable]
            Number of sampling steps for the diffusion process (default: 18)
        sigma_max: [Accepts: literal input, node input, place input. Discoverable]
            Maximum noise level for the diffusion process (default: 80.0)
        seed: [Accepts: literal input, node input, place input. Discoverable]
            Random seed for reproducibility (default: None)
        device: [Accepts: literal input, node input, place input. Discoverable]
            Device to use for model inference. Options: 'cuda', 'cuda:N', 'cpu', or None for auto-select

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.cbottle.CbottleInfilling'] = (
        'federation.fed.api.cbottle.CbottleInfilling'
    )
    __api_name__: Literal['cbottle.CbottleInfilling'] = 'cbottle.CbottleInfilling'
    dataset: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    input_variables: Union[List, NodeParam, PlaceParam, Advise]
    sampler_steps: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    sigma_max: Optional[Union[float, NodeParam, PlaceParam, Advise]] = None
    seed: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    device: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None


class CbottleSuperResolution(Operation):
    """
    Performs super-resolution on a low-resolution dataset using CBottleSR to produce high-resolution outputs

    Parameters:
        dataset: [Accepts: literal input, node input, place input. Discoverable]
            Input xarray.Dataset with variables and dims including 'time', 'lat', 'lon'
        output_resolution: [Accepts: literal input, node input, place input. Discoverable]
            Target high-resolution (nlat, nlon). If omitted, model default is used
        super_resolution_window: [Accepts: literal input, node input, place input. Discoverable]
            Optional geographic window (lat_s, lon_w, lat_n, lon_e) for regional SR
        sampler_steps: [Accepts: literal input, node input, place input. Discoverable]
            Number of sampling steps for the diffusion process (default: 18)
        sigma_max: [Accepts: literal input, node input, place input. Discoverable]
            Maximum noise level for the diffusion process (default: 800.0)
        seed: [Accepts: literal input, node input, place input. Discoverable]
            Random seed for reproducibility (default: None)
        device: [Accepts: literal input, node input, place input. Discoverable]
            Device to use for model inference. Options: 'cuda', 'cuda:N', 'cpu', or None for auto-select
        lat_lon: [Accepts: literal input, node input, place input. Discoverable]
            Whether to return data on a lat/lon grid or a nested HealPix grid (default: True)

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.cbottle.CbottleSuperResolution'] = (
        'federation.fed.api.cbottle.CbottleSuperResolution'
    )
    __api_name__: Literal['cbottle.CbottleSuperResolution'] = (
        'cbottle.CbottleSuperResolution'
    )
    dataset: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    output_resolution: Optional[Union[List, NodeParam, PlaceParam, Advise]] = None
    super_resolution_window: Optional[Union[List, NodeParam, PlaceParam, Advise]] = None
    sampler_steps: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    sigma_max: Optional[Union[float, NodeParam, PlaceParam, Advise]] = None
    seed: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    device: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
    lat_lon: Optional[Union[bool, NodeParam, PlaceParam, Advise]] = None


class CBottleTropicalCycloneGuidance(Operation):
    """
    Performs tropical cyclone guidance using CBottleTCGuidance model

    Parameters:
        lat_coords: [Accepts: literal input, node input, place input. Discoverable]
            List of latitude coordinates for tropical cyclone positions
        lon_coords: [Accepts: literal input, node input, place input. Discoverable]
            List of longitude coordinates for tropical cyclone positions
        times: [Accepts: literal input, node input, place input. Discoverable]
            List of datetime objects for the guidance times
        sampler_steps: [Accepts: literal input, node input, place input. Discoverable]
            Number of sampling steps for the diffusion process (default: 18)
        sigma_max: [Accepts: literal input, node input, place input. Discoverable]
            Maximum noise level for the diffusion process (default: 200.0)
        seed: [Accepts: literal input, node input, place input. Discoverable]
            Random seed for reproducibility (default: None)
        device: [Accepts: literal input, node input, place input. Discoverable]
            Device to use for model inference. Options: 'cuda', 'cuda:N', 'cpu', or None for auto-select
        lat_lon: [Accepts: literal input, node input, place input. Discoverable]
            Whether to return data on a lat/lon grid or a nested HealPix grid (default: True)

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal[
        'federation.fed.api.cbottle.CBottleTropicalCycloneGuidance'
    ] = 'federation.fed.api.cbottle.CBottleTropicalCycloneGuidance'
    __api_name__: Literal['cbottle.CBottleTropicalCycloneGuidance'] = (
        'cbottle.CBottleTropicalCycloneGuidance'
    )
    lat_coords: Union[List, NodeParam, PlaceParam, Advise]
    lon_coords: Union[List, NodeParam, PlaceParam, Advise]
    times: Union[List, NodeParam, PlaceParam, Advise]
    sampler_steps: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    sigma_max: Optional[Union[float, NodeParam, PlaceParam, Advise]] = None
    seed: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    device: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
    lat_lon: Optional[Union[bool, NodeParam, PlaceParam, Advise]] = None


class CbottleVideo(Operation):
    """
    Unrolls CBottle Video forecasts from an initial condition

    Parameters:
        dataset: [Accepts: literal input, node input, place input. Discoverable]
            Input xarray.Dataset with dims including 'time', 'lat', 'lon' and CBottle variables
        n_steps: [Accepts: literal input, node input, place input. Discoverable]
            Number of forecast steps to unroll (default: 12)
        seed: [Accepts: literal input, node input, place input. Discoverable]
            Optional RNG seed for reproducibility
        device: [Accepts: literal input, node input, place input. Discoverable]
            Device to use for inference (e.g., 'cuda', 'cuda:0', or 'cpu')
        lat_lon: [Accepts: literal input, node input, place input. Discoverable]
            Whether to return data on a lat/lon grid or a nested HealPix grid (default: True)

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.cbottle.CbottleVideo'] = (
        'federation.fed.api.cbottle.CbottleVideo'
    )
    __api_name__: Literal['cbottle.CbottleVideo'] = 'cbottle.CbottleVideo'
    dataset: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    n_steps: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    seed: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    device: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
    lat_lon: Optional[Union[bool, NodeParam, PlaceParam, Advise]] = None
