# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Any, Dict, Literal, Optional, Union

from nv_dfm_core.api import Advise, NodeParam, Operation, PlaceParam


class SfnoPrognostic(Operation):
    """
    Unrolls SFNO forecasts from an initial condition

    Parameters:
        dataset: [Accepts: literal input, node input, place input. Discoverable]
            Input xarray.Dataset with dims including 'time', 'lat', 'lon' and SFNO variables
        n_steps: [Accepts: literal input, node input, place input. Discoverable]
            Number of forecast steps to unroll (default: 12)
        seed: [Accepts: literal input, node input, place input. Discoverable]
            Optional RNG seed for reproducibility
        device: [Accepts: literal input, node input, place input. Discoverable]
            Device to use for inference (e.g., 'cuda', 'cuda:0', or 'cpu')

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.sfno.SfnoPrognostic'] = (
        'federation.fed.api.sfno.SfnoPrognostic'
    )
    __api_name__: Literal['sfno.SfnoPrognostic'] = 'sfno.SfnoPrognostic'
    dataset: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    n_steps: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    seed: Optional[Union[int, NodeParam, PlaceParam, Advise]] = None
    device: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
