# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from nv_dfm_core.api import Advise, NodeParam, Operation, PlaceParam


class ConvertToUint8(Operation):
    """
    Converts the xarray to uint8

    Parameters:
        data: [Accepts: literal input, node input, place input. Discoverable]
            The xarray to convert
        time_dimension: [Accepts: literal input, node input, place input. Discoverable]
            The name of the time dimension
        xydims: [Accepts: literal input, node input, place input. Discoverable]
            The names of the x and y dimensions
        min_value: [Accepts: literal input, node input, place input. Discoverable]
            The minimum value
        max_value: [Accepts: literal input, node input, place input. Discoverable]
            The maximum value

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.xarray.ConvertToUint8'] = (
        'federation.fed.api.xarray.ConvertToUint8'
    )
    __api_name__: Literal['xarray.ConvertToUint8'] = 'xarray.ConvertToUint8'
    data: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    time_dimension: Union[str, NodeParam, PlaceParam, Advise]
    xydims: Union[List, NodeParam, PlaceParam, Advise]
    min_value: Optional[Union[float, NodeParam, PlaceParam, Advise]] = None
    max_value: Optional[Union[float, NodeParam, PlaceParam, Advise]] = None


class RenderUint8ToImages(Operation):
    """
    Renders the uint8 to images

    Parameters:
        data: [Accepts: literal input, node input, place input. Discoverable]
            The xarray to render
        variable: [Accepts: literal input, node input, place input. Discoverable]
            The variable to render
        xydims: [Accepts: literal input, node input, place input. Discoverable]
            The names of the x and y dimensions
        time_dimension: [Accepts: literal input, node input, place input. Discoverable]
            The name of the time dimension
        additional_meta_data: [Accepts: literal input, node input, place input. Discoverable]
            Additional metadata to add to the texture file (JSON string)
        return_meta_data: [Accepts: literal input, node input, place input. Discoverable]
            Whether to return the metadata
        return_image_data: [Accepts: literal input, node input, place input. Discoverable]
            Whether to return the image data
        quality: [Accepts: literal input, node input, place input. Discoverable]
            The quality of the image
        format: [Accepts: literal input, node input, place input. Discoverable]
            The format of the image

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.xarray.RenderUint8ToImages'] = (
        'federation.fed.api.xarray.RenderUint8ToImages'
    )
    __api_name__: Literal['xarray.RenderUint8ToImages'] = 'xarray.RenderUint8ToImages'
    data: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    variable: Union[str, NodeParam, PlaceParam, Advise]
    xydims: Union[List, NodeParam, PlaceParam, Advise]
    time_dimension: Union[str, NodeParam, PlaceParam, Advise]
    additional_meta_data: Optional[
        Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    ] = None
    return_meta_data: Optional[Union[bool, NodeParam, PlaceParam, Advise]] = None
    return_image_data: Optional[Union[bool, NodeParam, PlaceParam, Advise]] = None
    quality: Optional[Union[float, NodeParam, PlaceParam, Advise]] = None
    format: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None


class VariableNorm(Operation):
    """
    Computes the p-norm of specified variables in a dataset

    Parameters:
        data: [Accepts: literal input, node input, place input. Discoverable]
            The xarray dataset to compute norm from
        variables: [Accepts: literal input, node input, place input. Discoverable]
            The list of variables to compute norm for
        output_name: [Accepts: literal input, node input, place input. Discoverable]
            The name of the output variable
        p: [Accepts: literal input, node input, place input. Discoverable]
            The p value for the norm calculation (default: 2.0)

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.xarray.VariableNorm'] = (
        'federation.fed.api.xarray.VariableNorm'
    )
    __api_name__: Literal['xarray.VariableNorm'] = 'xarray.VariableNorm'
    data: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    variables: Union[List, NodeParam, PlaceParam, Advise]
    output_name: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
    p: Optional[Union[float, NodeParam, PlaceParam, Advise]] = None
