# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

apiVersion: v2
name: earth2weatheranalytics
description: Earth-2 Omniverse Weather Analytics Blueprint
type: application

version: 1.0.111
appVersion: 1.0.111

home: https://github.com/NVIDIA-Omniverse-blueprints/earth2-weather-analytics
sources:
  - https://github.com/NVIDIA-Omniverse-blueprints/earth2-weather-analytics/deploy/helm

dependencies:
  - name: redis
    version: 19.1.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.bitnami
