# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

# Default values for dfm-process.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

streamer:
  enabled: true

nim:
  enabled: true
  overrideNgcAPIKey: ""
  shmSize: 4Gi

dfm:
  cacheSize: 64Gi


image:
  process:
    repository: earth2-weather-analytics-process
    tag: 0.2.0
    pullPolicy: IfNotPresent
  scheduler:
    repository: earth2-weather-analytics-scheduler
    tag: 0.2.0
    pullPolicy: IfNotPresent
  execute:
    repository: earth2-weather-analytics-execute
    tag: 0.2.0
    pullPolicy: IfNotPresent
  streamer:
    repository: earth2-weather-analytics-streamer
    tag: 0.3.0
    pullPolicy: IfNotPresent
  nim:
    repository: nvcr.io/nim/nvidia/fourcastnet
    tag: 1.0.0
    pullPolicy: IfNotPresent
  busybox:
    repository: earth2-weather-analytics-utils
    tag: busybox-1.36.1
    pullPolicy: IfNotPresent

# NVCF requirement
ngcImagePullSecretName: docker-secret
ngcImageRegistryPath: wf7ic9e2c5ge

service:
  process:
    type: ClusterIP
    port: 8080

  execute:
    type: ClusterIP
    port: 8085

  scheduler:
    type: ClusterIP
    port: 8082

  streamer:
    credsPort: 8011
    proxyPort: 49100

  nim:
    type: ClusterIP
    port: 8086

otel:
  collector: "http://jaeger-collector:4317"
  traces_exporter: none

resources: {}

execute:
  resources:
    limits:
      cpu: 2
      memory: 4G
    requests:
      cpu: 2
      memory: 4G

logging:
  json:
    enabled: false

auth:
  secret: dfm-auth-secret
  method:
    key: method
  api_key:
    key: api_key

redis:
  # TODO: Move the following values else where
  host: "{{ .Release.Name }}-redis-master"
  port: 6379
  db: 0
  # Turn off bitnami redis chart and use our own redis chart for NVCF
  bitnami: false
  # we expect a secret created that contains redis password
  secretName: redis
  secretKey: password

  usePassword: false
  usePasswordFiles: false

  image:
    # Not exactly like bitnami
    repository: earth2-weather-analytics-utils
    tag: redis-7.2.0

  auth:
    enabled: false

  networkPolicy:
    enabled: false

  master:
    enabled: false

  replica:
    enabled: false

# Additional volumes on the output Deployment definition.
volumes:
  - name: cache-volume
    persistentVolumeClaim:
      claimName: dfm-cache

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: cache-volume
    mountPath: /cache
    readOnly: false

site:
  name: mini1
  config:
    path: /etc/site-config
    file: config.yaml

  secrets:
    enabled: false
    path: /var/secrets
    name: dfm-execute-site-secrets
    file: secrets.json
