# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Literal

from ...api.cbottle import CbottleDataGen as CbottleDataGen_1
from ...api.cbottle import CbottleInfilling as CbottleInfilling_1
from ...api.cbottle import CbottleSuperResolution as CbottleSuperResolution_1
from ...api.cbottle import (
    CBottleTropicalCycloneGuidance as CBottleTropicalCycloneGuidance_1,
)
from ...api.cbottle import CbottleVideo as CbottleVideo_1


class CbottleDataGen(CbottleDataGen_1):
    """
    Generates synthetic climate data using CBottle3D diffusion model
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal['federation.fed.site.client1.cbottle.CbottleDataGen'] = (
        'federation.fed.site.client1.cbottle.CbottleDataGen'
    )
    __api_name__: Literal['cbottle.CbottleDataGen'] = 'cbottle.CbottleDataGen'


class CbottleInfilling(CbottleInfilling_1):
    """
    Performs infilling on a dataset using CBottleInfill model to generate additional climate variables
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal['federation.fed.site.client1.cbottle.CbottleInfilling'] = (
        'federation.fed.site.client1.cbottle.CbottleInfilling'
    )
    __api_name__: Literal['cbottle.CbottleInfilling'] = 'cbottle.CbottleInfilling'


class CbottleSuperResolution(CbottleSuperResolution_1):
    """
    Performs super-resolution on a low-resolution dataset using CBottleSR to produce high-resolution outputs
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal[
        'federation.fed.site.client1.cbottle.CbottleSuperResolution'
    ] = 'federation.fed.site.client1.cbottle.CbottleSuperResolution'
    __api_name__: Literal['cbottle.CbottleSuperResolution'] = (
        'cbottle.CbottleSuperResolution'
    )


class CBottleTropicalCycloneGuidance(CBottleTropicalCycloneGuidance_1):
    """
    Performs tropical cyclone guidance using CBottleTCGuidance model
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal[
        'federation.fed.site.client1.cbottle.CBottleTropicalCycloneGuidance'
    ] = 'federation.fed.site.client1.cbottle.CBottleTropicalCycloneGuidance'
    __api_name__: Literal['cbottle.CBottleTropicalCycloneGuidance'] = (
        'cbottle.CBottleTropicalCycloneGuidance'
    )


class CbottleVideo(CbottleVideo_1):
    """
    Unrolls CBottle Video forecasts from an initial condition
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal['federation.fed.site.client1.cbottle.CbottleVideo'] = (
        'federation.fed.site.client1.cbottle.CbottleVideo'
    )
    __api_name__: Literal['cbottle.CbottleVideo'] = 'cbottle.CbottleVideo'
