# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Literal

from ...api.dataloader import LoadCmip6Data as LoadCmip6Data_1
from ...api.dataloader import LoadEcmwfEra5Data as LoadEcmwfEra5Data_1
from ...api.dataloader import LoadGfsEra5Data as LoadGfsEra5Data_1
from ...api.dataloader import LoadHrrrEra5Data as LoadHrrrEra5Data_1


class LoadCmip6Data(LoadCmip6Data_1):
    """
    Loads the CMIP6 data
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal['federation.fed.site.client1.dataloader.LoadCmip6Data'] = (
        'federation.fed.site.client1.dataloader.LoadCmip6Data'
    )
    __api_name__: Literal['dataloader.LoadCmip6Data'] = 'dataloader.LoadCmip6Data'


class LoadEcmwfEra5Data(LoadEcmwfEra5Data_1):
    """
    Loads the ECMWF ERA5 data
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal[
        'federation.fed.site.client1.dataloader.LoadEcmwfEra5Data'
    ] = 'federation.fed.site.client1.dataloader.LoadEcmwfEra5Data'
    __api_name__: Literal['dataloader.LoadEcmwfEra5Data'] = (
        'dataloader.LoadEcmwfEra5Data'
    )


class LoadGfsEra5Data(LoadGfsEra5Data_1):
    """
    Loads the GFS ERA5 data
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal[
        'federation.fed.site.client1.dataloader.LoadGfsEra5Data'
    ] = 'federation.fed.site.client1.dataloader.LoadGfsEra5Data'
    __api_name__: Literal['dataloader.LoadGfsEra5Data'] = 'dataloader.LoadGfsEra5Data'


class LoadHrrrEra5Data(LoadHrrrEra5Data_1):
    """
    Loads the ERA5 data through HRRR
    """

    site: Literal['client1'] = 'client1'
    provider: None = None
    dfm_class_name: Literal[
        'federation.fed.site.client1.dataloader.LoadHrrrEra5Data'
    ] = 'federation.fed.site.client1.dataloader.LoadHrrrEra5Data'
    __api_name__: Literal['dataloader.LoadHrrrEra5Data'] = 'dataloader.LoadHrrrEra5Data'
