{{- if not .Values.redis.bitnami }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-headless
  namespace: "{{ .Release.namespace }}"
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.2.4
    helm.sh/chart: redis-19.1.5
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-redis
      port: {{ .Values.redis.port }}
      targetPort: redis
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: redis
{{- end }}
