{{- if not .Values.redis.bitnami }}
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.redis.host . | quote }}
  namespace: "{{ .Release.namespace }}"
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.2.4
    helm.sh/chart: redis-19.1.5
    app.kubernetes.io/component: master
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    - name: tcp-redis
      port: {{ .Values.redis.port }}
      targetPort: redis
      nodePort: null
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: master
{{- end }}
