# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
THIS FILE WAS GENERATED BY DFM-APIGEN. DO NOT MODIFY.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from nv_dfm_core.api import Advise, NodeParam, Operation, PlaceParam


class LoadCmip6Data(Operation):
    """
    Loads the CMIP6 data

    Parameters:
        variables: [Accepts: literal input, node input, place input. Discoverable]
            The variables to load
        selection: [Accepts: literal input, node input, place input. Discoverable]
            The selection to load
        experiment_id: [Accepts: literal input, node input, place input. Discoverable]
            The experiment ID
        source_id: [Accepts: literal input, node input, place input. Discoverable]
            The source ID
        table_id: [Accepts: literal input, node input, place input. Discoverable]
            The table ID
        variant_label: [Accepts: literal input, node input, place input. Discoverable]
            The variant label
        invalidate_cache: [Accepts: literal input, node input, place input. Discoverable]
            Whether to invalidate the cache

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.dataloader.LoadCmip6Data'] = (
        'federation.fed.api.dataloader.LoadCmip6Data'
    )
    __api_name__: Literal['dataloader.LoadCmip6Data'] = 'dataloader.LoadCmip6Data'
    variables: Union[List, NodeParam, PlaceParam, Advise]
    selection: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    experiment_id: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
    source_id: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
    table_id: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
    variant_label: Optional[Union[str, NodeParam, PlaceParam, Advise]] = None
    invalidate_cache: Optional[Union[bool, NodeParam, PlaceParam, Advise]] = None


class LoadEcmwfEra5Data(Operation):
    """
    Loads the ECMWF ERA5 data

    Parameters:
        variables: [Accepts: literal input, node input, place input. Discoverable]
            The variables to load
        selection: [Accepts: literal input, node input, place input. Discoverable]
            The selection to load

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.dataloader.LoadEcmwfEra5Data'] = (
        'federation.fed.api.dataloader.LoadEcmwfEra5Data'
    )
    __api_name__: Literal['dataloader.LoadEcmwfEra5Data'] = (
        'dataloader.LoadEcmwfEra5Data'
    )
    variables: Union[List, NodeParam, PlaceParam, Advise]
    selection: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]


class LoadGfsEra5Data(Operation):
    """
    Loads the GFS ERA5 data using Earth2Studio backend

    Parameters:
        variables: [Accepts: literal input, node input, place input. Discoverable]
            The variables to load
        selection: [Accepts: literal input, node input, place input. Discoverable]
            The selection to load (time required, optional mode and timeout)
        invalidate_cache: [Accepts: literal input, node input, place input. Discoverable]
            Whether to invalidate the cache

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.dataloader.LoadGfsEra5Data'] = (
        'federation.fed.api.dataloader.LoadGfsEra5Data'
    )
    __api_name__: Literal['dataloader.LoadGfsEra5Data'] = 'dataloader.LoadGfsEra5Data'
    variables: Union[List, NodeParam, PlaceParam, Advise]
    selection: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    invalidate_cache: Optional[Union[bool, NodeParam, PlaceParam, Advise]] = None


class LoadHrrrEra5Data(Operation):
    """
    Loads ERA5 data through HRRR

    Parameters:
        variables: [Accepts: literal input, node input, place input. Discoverable]
            The variables to load
        selection: [Accepts: literal input, node input, place input. Discoverable]
            The selection to load
        invalidate_cache: [Accepts: literal input, node input, place input. Discoverable]
            Whether to invalidate the cache

    Returns: object
    """

    class Config:
        arbitrary_types_allowed = True

    dfm_class_name: Literal['federation.fed.api.dataloader.LoadHrrrEra5Data'] = (
        'federation.fed.api.dataloader.LoadHrrrEra5Data'
    )
    __api_name__: Literal['dataloader.LoadHrrrEra5Data'] = 'dataloader.LoadHrrrEra5Data'
    variables: Union[List, NodeParam, PlaceParam, Advise]
    selection: Union[Dict[str, Any], NodeParam, PlaceParam, Advise]
    invalidate_cache: Optional[Union[bool, NodeParam, PlaceParam, Advise]] = None
